# Generated by Django 5.0.9 on 2024-09-27 06:33

import django.db.models.deletion
import posts.models
import posts.service
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, verbose_name='created_at')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('description', models.CharField(verbose_name='description')),
                ('text', models.TextField(verbose_name='text')),
                ('image', models.ImageField(blank=True, null=True, upload_to=posts.models.get_upload_path, verbose_name='image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
