version: '3.7'
services:
  app:
    tty: True
    build: .
    command: 
      bash -c "python manage.py migrate ;
      python manage.py create_initial_data ;
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
  db:
    tty: True
    stdin_open: true
    image: postgres:15
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $PG_USER" ]
